LIB-40 Unique Transfer Manager
simplymadeapps/simple-logger pull request #27
Opened 2020-10-20 19:37 UTC by billburgess

2020-10-27 14:10 UTC, bmedenwald commented
Prove how this works first before we code the solution.

2020-10-29 16:15 UTC, bmedenwald requested changes
I'll give you these now, but know there are a few left possibly.

2020-10-29 16:15 UTC, bmedenwald commented on SimpleLogger/AmazonUploader.m
> +    [self removePreviousTransferUtilityIfNeeded];
Hand the awsConfigurationKey to this method so it doesn't need to look it up itself.

2020-10-29 16:15 UTC, bmedenwald commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +        XCTAssertEqual(config.regionType, AWSRegionUSEast1);
Can you inspect provider?

`XCTAssertEqual(config.provider, providerMock);`

2020-10-29 18:44 UTC, billburgess commented on SimpleLogger/AmazonUploader.m
> +    logger.awsConfigurationKey = [NSString stringWithFormat:@"SimpleLogger.AWS.ConfigKey.%@",[NSUUID UUID].UUIDString];
Done

2020-10-29 18:46 UTC, billburgess commented on SimpleLogger/AmazonUploader.m
>      AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:provider];
Done

2020-10-29 19:05 UTC, billburgess commented on SimpleLogger/AmazonUploader.m
> +    [self removePreviousTransferUtilityIfNeeded];
Done

2020-10-29 19:07 UTC, billburgess commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +        XCTAssertEqual(config.regionType, AWSRegionUSEast1);
I guess I can. Done.

2020-10-30 15:39 UTC, bmedenwald requested changes

2020-10-30 15:39 UTC, bmedenwald commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    // mock initialize to avoid crashing with bad data
I don't understand why you would need to expect `initializeAmazonUploadProvider` in this method.

2020-10-30 15:39 UTC, bmedenwald commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    SimpleLogger *logger = [SimpleLogger sharedLogger];
Below you did this:

`[SimpleLogger initWithAWSRegion:AWSRegionUSEast1 bucket:@"bucket" accessToken:@"access" secret:@"secret"];`

Can you do that here too in order to make this mocking smaller?

2020-10-30 15:39 UTC, bmedenwald commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    [[[transferMock stub] andReturn:utility] S3TransferUtilityForKey:@"SimpleLoggerTransferUtility"];
I cannot see where "SimpleLoggerTransferUtility" is being set or how that works. Should this instead be `[SimpleLogger sharedLogger].awsConfigurationKey`? Otherwise, I assume this stub is not even being used.

In fact, this whole test may be a bit off. If you mock the transferUtility, you should be able to expect that your transferMock (which is standing in for the transferUtility receives an `uploadFile` with arguments that you expect.

I don't think you need `utilityMock` at all as long as you can move those assertions to the transfer mock.

Also, the assertions for `uploadFile` arguments should get specific instead of `[OCMArg any]`. You likely need to stub in `AmazonUploader`, but that should be doable.

2020-10-30 15:39 UTC, bmedenwald commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    XCTAssertNotNil(utility);
Do you have to do this to bootstrap this somehow? You don't need the assertion for your tests,

2020-11-02 17:06 UTC, billburgess commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    XCTAssertTrue([[AmazonUploader configKey] containsString:@"SimpleLogger.AWS.ConfigKey."]);
Done. We don't use Nimble in this project yet, went with standard mocking for UUID.

2020-11-02 17:16 UTC, billburgess commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    // mock initialize to avoid crashing with bad data
I rewrote this test to match the way the other tests set up the data. This was a problem before because calling the helper method to set the values (rather than manually setting) calls into initializeAmazonUploadProvider and crashes with the 0 for region.

2020-11-02 17:18 UTC, billburgess commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    SimpleLogger *logger = [SimpleLogger sharedLogger];
I think I'd prefer to leave it. Calling this method recursively calls back into the method I'm trying to test. This also prevents crashes if I fill with invalid or bogus data that Amazon doesn't like. It's more lines, but less mocking. See the fixed test from the previous comment.

2020-11-02 17:34 UTC, billburgess commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    [[[transferMock stub] andReturn:utility] S3TransferUtilityForKey:@"SimpleLoggerTransferUtility"];
The S3 transfer utility is generated with the AWS library when I set my region, bucket, access, and secret. That method calls into initializeAmazonUploader. This gives me an instance of the transfer utility I can pull back out and mock when this method gets called. That same transfer manager lives until it gets removed manually or the app is closed.

I can't move the assertions to the transferMock. transferMock returns an instance transfer manager. I can't mock the uploadFile on that class, that needs to be done on the transfer utility instance which are contained on the utilityMock. 

I added additional mocking for the parameters to make sure each one is covered.

2020-11-02 17:38 UTC, billburgess commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    XCTAssertNotNil(utility);
Not needed. I think it got left behind when I was testing if that mocking method would even work. Removed.

2020-11-02 21:43 UTC, bmedenwald requested changes

2020-11-02 21:43 UTC, bmedenwald commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    SimpleLogger *logger = [SimpleLogger sharedLogger];
Can this be folded up to the smaller declaration you are doing everywhere else as well?

2020-11-02 21:43 UTC, bmedenwald commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    [[[transferMock stub] andReturn:utility] S3TransferUtilityForKey:@"SimpleLoggerTransferUtility"];
I still don't understand where "SimpleLoggerTransferUtility" is coming from. It's a string, but I don't see you using it anywhere else in this test/file. Why will transferMock receive `S3TransferUtilityForKey:@"SimpleLoggerTransferUtility"`?

2020-11-02 22:04 UTC, billburgess commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    SimpleLogger *logger = [SimpleLogger sharedLogger];
No, we are testing that the BOOL helper method works. If we use the shorter method, it calls into the init of the amazon stuff and will crash with our bogus stuff. We need to manually set them to ensure we don't pass crap into amazon and fail a test.

2020-11-02 22:08 UTC, billburgess commented on SimpleLoggerExample/SimpleLoggerTests/AmazonUploaderTests.m
> +    [[[transferMock stub] andReturn:utility] S3TransferUtilityForKey:@"SimpleLoggerTransferUtility"];
I see. I missed that string key. That was the old hardcoded string for the transfer manager. So it was skipping this stub and just grabbing it from amazon instead of my stub. Amazon must return the same object each time because this works by grabbing it from Amazon and mocking it and removing the old transferMock.

2020-11-04 13:41 UTC, bmedenwald approved these changes

2020-11-04 14:14 UTC, merged