LIB-42 Reorder files and minor cleanup
simplymadeapps/simple-logger pull request #29
Opened 2021-02-01 20:22 UTC by billburgess

In order to have this be a public repo the project needs to pass `pod spec lint`. Due to the way the files were organized and the internal testing pods used, this command fails since it can't find the project. I moved the main project files out into the main directory and cleaned up the broken Xcode links to the example/test project. Most of the files changed due to rename/relocate. Once this change is approved, we can update the Specs to use this version as the latest and make it public.

2021-02-03 21:56 UTC, bmedenwald requested changes

2021-02-03 21:56 UTC, bmedenwald commented on .travis.yml
>          - curl -s https://codecov.io/bash | bash -s - -v -f test-reports/cobertura.xml -X coveragepy -X gcov -X xcode
Empty final line missing.

2021-02-03 21:56 UTC, bmedenwald commented on Podfile
> +source 'https://cdn.cocoapods.org/'
Isn't this the default now?

2021-02-03 21:56 UTC, bmedenwald commented on SimpleLoggerExample/Assets.xcassets/AppIcon.appiconset/Contents.json
> -{
Why was there in here and why is it not needed any longer?

2021-02-03 22:12 UTC, billburgess commented on .travis.yml
>          - curl -s https://codecov.io/bash | bash -s - -v -f test-reports/cobertura.xml -X coveragepy -X gcov -X xcode
Done

2021-02-03 22:13 UTC, billburgess commented on Podfile
> +source 'https://cdn.cocoapods.org/'
This is the default. This should ensure pod install goes much faster without the need for --repo-update.

2021-02-03 22:16 UTC, billburgess commented on SimpleLoggerExample/Assets.xcassets/AppIcon.appiconset/Contents.json
> -{
The example project used to hold the project and tests automatically includes it. It is not necessary for the example app or for testing. I removed it since I was moving all the files around anyway. No reason to include anything not needed.

2021-02-04 21:41 UTC, bmedenwald requested changes

2021-02-04 21:41 UTC, bmedenwald commented on .travis.yml
> +
Something's still wrong, likely you have empty space on line 39 and no empty line still.

2021-02-08 19:52 UTC, billburgess commented on .travis.yml
> +
That was way dumber and harder than it should be to put a newline at the end. VS Code said it was, but it wasn't. Tried Atom, did the same thing. Eventually had to use TextEdit on Mac to save a newline at the end. Not sure what was up with this file or format, but the "smart" editors got it wrong. Should be fixed now.

2021-02-08 19:55 UTC, bmedenwald approved these changes

2021-02-08 20:10 UTC, merged